import { GoogleCloudService, AzureCloudProduct, AzureCloudRegion,AmazonCloudService,AmazonCloudRegion } from "../types.ts";

// @formatter:off

// Amazon Cloud types ======================================================================
export const amazonCloudDefaultServices: AmazonCloudService[] = [
  { name: "EC2",          serviceId: "AmazonEC2",       displayName: "Amazon Elastic Compute Cloud",                    active:true, scrapePerRegion:true },
  { name: "RDS",          serviceId: "AmazonRDS",       displayName: "Amazon Relational Database Service",              active:true, scrapePerRegion:true },
  { name: "S3",           serviceId: "AmazonS3",        displayName: "Amazon Simple Storage Service",                   active:true, scrapePerRegion:false },
  { name: "EKS",          serviceId: "AmazonEKS",       displayName: "Amazon Elastic Container Service for Kubernetes", active:true, scrapePerRegion:false },
  { name: "DataTransfer", serviceId: "AWSDataTransfer", displayName: "AWS Data Transfer",                               active:true, scrapePerRegion:false },
] as const;

export const amazonCloudDefaultRegions: AmazonCloudRegion[] = [
  { name: "af-south-1",     displayName: "Ciudad del Cabo",             regionalDisplayName: "(África) Ciudad del Cabo",              regionalName: "África",        active: true },
  { name: "ap-east-1",      displayName: "Hong Kong",                   regionalDisplayName: "(Asia Pacífico) Hong Kong",             regionalName: "Asia Pacífico", active: true },
  { name: "ap-northeast-1", displayName: "Tokio",                       regionalDisplayName: "(Asia Pacífico) Tokio",                 regionalName: "Asia Pacífico", active: true },
  { name: "ap-northeast-2", displayName: "Seúl",                        regionalDisplayName: "(Asia Pacífico) Seúl",                  regionalName: "Asia Pacífico", active: true },
  { name: "ap-northeast-3", displayName: "Osaka",                       regionalDisplayName: "(Asia Pacífico) Osaka",                 regionalName: "Asia Pacífico", active: true },
  { name: "ap-south-1",     displayName: "Mumbai",                      regionalDisplayName: "(Asia Pacífico) Mumbai",                regionalName: "Asia Pacífico", active: true },
  { name: "ap-south-2",     displayName: "Hyderabad",                   regionalDisplayName: "(Asia Pacífico) Hyderabad",             regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-1", displayName: "Singapur",                    regionalDisplayName: "(Asia Pacífico) Singapur",              regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-2", displayName: "Sídney",                      regionalDisplayName: "(Asia Pacífico) Sídney",                regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-3", displayName: "Yakarta",                     regionalDisplayName: "(Asia Pacífico) Yakarta",               regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-4", displayName: "Melbourne",                   regionalDisplayName: "(Asia Pacífico) Melbourne",             regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-5", displayName: "Malasia",                     regionalDisplayName: "(Asia Pacífico) Malasia",               regionalName: "Asia Pacífico", active: true },
  { name: "ap-southeast-7", displayName: "Tailandia",                   regionalDisplayName: "(Asia Pacífico) Tailandia",             regionalName: "Asia Pacífico", active: true },
  { name: "ca-central-1",   displayName: "Centro",                      regionalDisplayName: "(Canadá) Centro",                       regionalName: "América",       active: true },
  { name: "ca-west-1",      displayName: "Este",                        regionalDisplayName: "(Canadá) Este",                         regionalName: "América",       active: true },
  { name: "cn-north-1",     displayName: "Beijing",                     regionalDisplayName: "(China) Beijing",                       regionalName: "Asia Pacífico", active: false },
  { name: "cn-northwest-1", displayName: "Ningxia",                     regionalDisplayName: "(China) Ningxia",                       regionalName: "Asia Pacífico", active: false },
  { name: "eu-central-1",   displayName: "Fráncfort",                   regionalDisplayName: "(Europa) Fráncfort",                    regionalName: "Europa",        active: true },
  { name: "eu-central-2",   displayName: "Zúrich",                      regionalDisplayName: "(Europa) Zúrich",                       regionalName: "Europa",        active: true },
  { name: "eu-north-1",     displayName: "Estocolmo",                   regionalDisplayName: "(Europa) Estocolmo",                    regionalName: "Europa",        active: true },
  { name: "eu-south-1",     displayName: "Milán",                       regionalDisplayName: "(Europa) Milán",                        regionalName: "Europa",        active: true },
  { name: "eu-south-2",     displayName: "España",                      regionalDisplayName: "(Europa) España",                       regionalName: "Europa",        active: true },
  { name: "eu-west-1",      displayName: "Irlanda",                     regionalDisplayName: "(Europa) Irlanda",                      regionalName: "Europa",        active: true },
  { name: "eu-west-2",      displayName: "Londres",                     regionalDisplayName: "(Europa) Londres",                      regionalName: "Europa",        active: true },
  { name: "eu-west-3",      displayName: "París",                       regionalDisplayName: "(Europa) París",                        regionalName: "Europa",        active: true },
  { name: "il-central-1",   displayName: "Tel Aviv",                    regionalDisplayName: "(Israel) Tel Aviv",                     regionalName: "Oriente Medio", active: true },
  { name: "me-central-1",   displayName: "EAU",                         regionalDisplayName: "(Oriente Medio) EAU",                   regionalName: "Oriente Medio", active: true },
  { name: "me-south-1",     displayName: "Baréin",                      regionalDisplayName: "(Oriente Medio) Baréin",                regionalName: "Oriente Medio", active: true },
  { name: "mx-central-1",   displayName: "Centro",                      regionalDisplayName: "(Mexico) Centro",                       regionalName: "América",       active: true },
  { name: "sa-east-1",      displayName: "São Paulo",                   regionalDisplayName: "(América del Sur) São Paulo",           regionalName: "América",       active: true },
  { name: "us-east-1",      displayName: "Este - Norte de Virginia",    regionalDisplayName: "(EE.UU.) Este - Norte de Virginia",     regionalName: "América",       active: true },
  { name: "us-east-2",      displayName: "Este - Ohio",                 regionalDisplayName: "(EE.UU.) Este - Ohio",                  regionalName: "América",       active: true },
  { name: "us-gov-east-1",  displayName: "Este AWS GovCloud",           regionalDisplayName: "(EE.UU.) Este AWS GovCloud",            regionalName: "América",       active: false },
  { name: "us-gov-west-1",  displayName: "Oeste AWS GovCloud",          regionalDisplayName: "(EE.UU.) Oeste AWS GovCloud",           regionalName: "América",       active: false },
  { name: "us-west-1",      displayName: "Oeste - Norte de California", regionalDisplayName: "(EE.UU.) Oeste - Norte de California",  regionalName: "América",       active: true },
  { name: "us-west-2",      displayName: "Oeste - Oregón",              regionalDisplayName: "(EE.UU.) Oeste - Oregón",               regionalName: "América",       active: true }
] as const;
// Azure Cloud types ======================================================================

export const azureCloudDefaultRegions: AzureCloudRegion[] = [
  { name: "eastus",             displayName: "East US",               regionalDisplayName: "(EE.UU.) East US",                       regionalName: "América",       active: true },
  { name: "eastus2",            displayName: "East US 2",             regionalDisplayName: "(EE.UU.) East US 2",                     regionalName: "América",       active: true },
  { name: "southcentralus",     displayName: "South Central US",      regionalDisplayName: "(EE.UU.) South Central US",              regionalName: "América",       active: true },
  { name: "westus2",            displayName: "West US 2",             regionalDisplayName: "(EE.UU.) West US 2",                     regionalName: "América",       active: true },
  { name: "westus3",            displayName: "West US 3",             regionalDisplayName: "(EE.UU.) West US 3",                     regionalName: "América",       active: true },
  { name: "australiaeast",      displayName: "Australia East",        regionalDisplayName: "(Asia Pacífico) Australia East",         regionalName: "Asia Pacífico", active: true },
  { name: "southeastasia",      displayName: "Southeast Asia",        regionalDisplayName: "(Asia Pacífico) Southeast Asia",         regionalName: "Asia Pacífico", active: true },
  { name: "northeurope",        displayName: "North Europe",          regionalDisplayName: "(Europa) North Europe",                  regionalName: "Europa",        active: true },
  { name: "swedencentral",      displayName: "Sweden Central",        regionalDisplayName: "(Europa) Sweden Central",                regionalName: "Europa",        active: true },
  { name: "uksouth",            displayName: "UK South",              regionalDisplayName: "(Europa) UK South",                      regionalName: "Europa",        active: true },
  { name: "westeurope",         displayName: "West Europe",           regionalDisplayName: "(Europa) West Europe",                   regionalName: "Europa",        active: true },
  { name: "centralus",          displayName: "Central US",            regionalDisplayName: "(EE.UU.) Central US",                    regionalName: "América",       active: true },
  { name: "southafricanorth",   displayName: "South Africa North",    regionalDisplayName: "(África) South Africa North",            regionalName: "África",        active: true },
  { name: "centralindia",       displayName: "Central India",         regionalDisplayName: "(Asia Pacífico) Central India",          regionalName: "Asia Pacífico", active: true },
  { name: "eastasia",           displayName: "East Asia",             regionalDisplayName: "(Asia Pacífico) East Asia",              regionalName: "Asia Pacífico", active: true },
  { name: "japaneast",          displayName: "Japan East",            regionalDisplayName: "(Asia Pacífico) Japan East",             regionalName: "Asia Pacífico", active: true },
  { name: "koreacentral",       displayName: "Korea Central",         regionalDisplayName: "(Asia Pacífico) Korea Central",          regionalName: "Asia Pacífico", active: true },
  { name: "canadacentral",      displayName: "Canada Central",        regionalDisplayName: "(Canada) Canada Central",                regionalName: "América",      active: true },
  { name: "francecentral",      displayName: "France Central",        regionalDisplayName: "(Europa) France Central",                regionalName: "Europa",        active: true },
  { name: "germanywestcentral", displayName: "Germany West Central",  regionalDisplayName: "(Europa) Germany West Central",          regionalName: "Europa",        active: true },
  { name: "italynorth",         displayName: "Italy North",           regionalDisplayName: "(Europa) Italy North",                   regionalName: "Europa",        active: true },
  { name: "norwayeast",         displayName: "Norway East",           regionalDisplayName: "(Europa) Norway East",                   regionalName: "Europa",        active: true },
  { name: "polandcentral",      displayName: "Poland Central",        regionalDisplayName: "(Europa) Poland Central",                regionalName: "Europa",        active: true },
  { name: "spaincentral",       displayName: "Spain Central",         regionalDisplayName: "(Europa) Spain Central",                 regionalName: "Europa",        active: true },
  { name: "switzerlandnorth",   displayName: "Switzerland North",     regionalDisplayName: "(Europa) Switzerland North",             regionalName: "Europa",        active: true },
  { name: "mexicocentral",      displayName: "Mexico Central",        regionalDisplayName: "(Mexico) Mexico Central",                regionalName: "América",       active: true },
  { name: "uaenorth",           displayName: "UAE North",             regionalDisplayName: "(Oriente Medio) UAE North",              regionalName: "Oriente Medio",   active: true },
  { name: "brazilsouth",        displayName: "Brazil South",          regionalDisplayName: "(América del Sur) Brazil South",         regionalName: "América",       active: true },
  { name: "israelcentral",      displayName: "Israel Central",        regionalDisplayName: "(Oriente Medio) Israel Central",         regionalName: "Oriente Medio",   active: true },
  { name: "qatarcentral",       displayName: "Qatar Central",         regionalDisplayName: "(Oriente Medio) Qatar Central",          regionalName: "Oriente Medio",   active: true },
  { name: "newzealand",         displayName: "New Zealand",           regionalDisplayName: "(Asia Pacífico) New Zealand",            regionalName: "Asia Pacífico", active: false },
  { name: "northcentralus",     displayName: "North Central US",      regionalDisplayName: "(EE.UU.) North Central US",              regionalName: "América",       active: true },
  { name: "westus",             displayName: "West US",               regionalDisplayName: "(EE.UU.) West US",                       regionalName: "América",       active: true },
  { name: "japanwest",          displayName: "Japan West",            regionalDisplayName: "(Asia Pacífico) Japan West",             regionalName: "Asia Pacífico", active: true },
  { name: "westcentralus",      displayName: "West Central US",       regionalDisplayName: "(EE.UU.) West Central US",               regionalName: "América",       active: true },
  { name: "australiacentral",   displayName: "Australia Central",     regionalDisplayName: "(Asia Pacífico) Australia Central",      regionalName: "Asia Pacífico", active: true },
  { name: "australiasoutheast", displayName: "Australia Southeast",   regionalDisplayName: "(Asia Pacífico) Australia Southeast",    regionalName: "Asia Pacífico", active: true },
  { name: "koreasouth",         displayName: "Korea South",           regionalDisplayName: "(Asia Pacífico) Korea South",            regionalName: "Asia Pacífico", active: true },
  { name: "southindia",         displayName: "South India",           regionalDisplayName: "(Asia Pacífico) South India",            regionalName: "Asia Pacífico", active: true },
  { name: "westindia",          displayName: "West India",            regionalDisplayName: "(Asia Pacífico) West India",             regionalName: "Asia Pacífico", active: true },
  { name: "canadaeast",         displayName: "Canada East",           regionalDisplayName: "(Canada) Canada East",                   regionalName: "América",       active: true },
  { name: "ukwest",             displayName: "UK West",               regionalDisplayName: "(Europa) UK West",                       regionalName: "Europa",         active: true }
] as const;

export const azureCloudDefaultProducts: AzureCloudProduct[] = [
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Basv2 Series",                                                       productId: "DZH318Z0K9JH", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Bsv2 Series",                                                        productId: "DZH318Z0K9K9", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dasv4 Series",                                                       productId: "DZH318Z0CM2C", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dasv5 Series",                                                       productId: "DZH318Z08W0T", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dasv6 Series",                                                       productId: "DZH318Z0DWTB", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dav4 Series",                                                        productId: "DZH318Z0CM2B", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Lsv3 Series",                                                        productId: "DZH318Z08NR7", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines MdSv2 Series",                                                       productId: "DZH318Z08LV1", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Ev5 Series",                                                         productId: "DZH318Z08M9J", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Edv5 Series",                                                        productId: "DZH318Z08M9R", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dsv5 Series",                                                        productId: "DZH318Z08M9W", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dsv6 Series",                                                        productId: "DZH318Z0GNHB", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dv5 Series",                                                         productId: "DZH318Z08M9X", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Easv5 Series",                                                       productId: "DZH318Z093WZ", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Easv6 Series",                                                       productId: "DZH318Z0F5F1", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Edsv5 Series",                                                       productId: "DZH318Z096SN", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Edsv6 Series",                                                       productId: "DZH318Z0GNHM", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Esv5 Series",                                                        productId: "DZH318Z096SR", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Esv6 Series",                                                        productId: "DZH318Z0GNH6", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Av2 Series",                                                         productId: "DZH318Z0BPRJ", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dv2 Series",                                                         productId: "DZH318Z0BQ34", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines DSv2 Series",                                                        productId: "DZH318Z0BQ4C", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dv3 Series",                                                         productId: "DZH318Z0BQ4K", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Ev3 Series",                                                         productId: "DZH318Z0BQ4L", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines ESv3 Series",                                                        productId: "DZH318Z0BQ4R", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines MS Series",                                                          productId: "DZH318Z0BQ4W", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines FSv2 Series",                                                        productId: "DZH318Z0BQ4X", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Fasv6 Series",                                                       productId: "DZH318Z0FXXJ", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines DSv3 Series",                                                        productId: "DZH318Z0BQ50", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines LSv2 Series",                                                        productId: "DZH318Z0BQM3", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Mv2/MSv2 Series",                                                    productId: "DZH318Z0BX5L", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Eav4 Series",                                                        productId: "DZH318Z0CM29", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Easv4 Series",                                                       productId: "DZH318Z0CM2D", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dsv4 Series",                                                        productId: "DZH318Z0CSHJ", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Edsv4 Series",                                                       productId: "DZH318Z0CSHK", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Esv4 Series",                                                        productId: "DZH318Z0CSHL", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Dv4 Series",                                                         productId: "DZH318Z0D1L4", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Edv4 Series",                                                        productId: "DZH318Z0D1L5", active: true },
  { serviceId: "DZH313Z7MMC8", serviceName: "Virtual Machines",               productName: "Virtual Machines Ev4 Series",                                                         productId: "DZH318Z0D1L7", active: true },
  { serviceId: "DZH315HTQSK6", serviceName: "Azure Kubernetes Service",       productName: "Azure Kubernetes Service",                                                            productId: "DZH318Z0CQSH", active: true },
  { serviceId: "DZH317F1HKN0", serviceName: "Storage",                        productName: "Premium SSD Managed Disks",                                                           productId: "DZH318Z0BP04", active: true },
  { serviceId: "DZH317F1HKN0", serviceName: "Storage",                        productName: "Files v2",                                                                            productId: "DZH318Z0BP09", active: true },
  { serviceId: "DZH317F1HKN0", serviceName: "Storage",                        productName: "Standard HDD Managed Disks",                                                          productId: "DZH318Z0BP0L", active: true },
  { serviceId: "DZH317F1HKN0", serviceName: "Storage",                        productName: "Standard SSD Managed Disks",                                                          productId: "DZH318Z0BP88", active: true },
  { serviceId: "DZH317F1HKN0", serviceName: "Storage",                        productName: "General Block Blob v2",                                                               productId: "DZH318Z0BPH7", active: true },
  { serviceId: "DZH318FHKQ5W", serviceName: "Bandwidth",                      productName: "Bandwidth - Routing Preference: Internet",                                            productId: "DZH318Z0C8ZQ", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server Memory Optimized Edsv4 Series Compute", productId: "DZH318Z09SM1", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server General Purpose Ddsv4 Series Compute",  productId: "DZH318Z09SM2", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server Backup Storage",                        productId: "DZH318Z0DCRW", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server Storage",                               productId: "DZH318Z0DCRX", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server Memory Optimized Esv3 Series Compute",  productId: "DZH318Z0DCRZ", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Flexible Server General Purpose Dsv3 Series Compute",   productId: "DZH318Z0DCS1", active: true },
  { serviceId: "DZH3199QPQTD", serviceName: "Azure Database for PostgreSQL",  productName: "Azure Database for PostgreSQL Standard Storage",                                      productId: "DZH318Z0C16N", active: true },
] as const;

// Google Cloud types ======================================================================

export const googleCloudDefaultServices: GoogleCloudService[] = [
  { name: "ComputeEngine", serviceId: "6F81-5844-456A", displayName: "Compute Engine",    active: true },
  { name: "CloudStorage",  serviceId: "95FF-2EF5-5EA1", displayName: "Cloud Storage",     active: true },
  { name: "CloudSQL",      serviceId: "9662-B51E-5089", displayName: "Cloud SQL",         active: true },
  { name: "GKE",           serviceId: "CCD8-9BF1-090E", displayName: "Kubernetes Engine", active: true },
] as const;

export const googleCloudDefaultRegions: GoogleCloudRegion[] = [
  {name: 'africa-south1',           displayName: 'South Africa, Johannesburg',    regionalDisplayName: '(África) South Africa, Johannesburg',       regionalName: 'África',        active: false },
  {name: 'asia-east1',              displayName: 'Taiwan, Changhua County',       regionalDisplayName: '(Asia Pacífico) Taiwan, Changhua County',   regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-east2',              displayName: 'Hong Kong',                     regionalDisplayName: '(Asia Pacífico) Hong Kong',                 regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-northeast1',         displayName: 'Japan,Tokyo',                   regionalDisplayName: '(Asia Pacífico) Japan,Tokyo',               regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-northeast2',         displayName: 'Japan, Osaka',                  regionalDisplayName: '(Asia Pacífico) Japan, Osaka',              regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-northeast3',         displayName: 'South Korea,Seoul',             regionalDisplayName: '(Asia Pacífico) South Korea,Seoul',         regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-south1',             displayName: 'India, Mumbai',                 regionalDisplayName: '(Asia Pacífico) India, Mumbai',             regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-south2',             displayName: 'India, Delhi',                  regionalDisplayName: '(Asia Pacífico) India, Delhi',              regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-southeast1',         displayName: 'Singapore, Jurong West',        regionalDisplayName: '(Asia Pacífico) Singapore, Jurong West',    regionalName: 'Asia Pacífico', active: true },
  {name: 'asia-southeast2',         displayName: 'Indonesia, Jakarta',            regionalDisplayName: '(Asia Pacífico) Indonesia, Jakarta',        regionalName: 'Asia Pacífico', active: true },
  {name: 'australia-southeast1',    displayName: 'Australia, Sydney',             regionalDisplayName: '(Asia Pacífico) Australia, Sydney',         regionalName: 'Asia Pacífico', active: true },
  {name: 'australia-southeast2',    displayName: 'Australia, Melbourne',          regionalDisplayName: '(Asia Pacífico) Australia, Melbourne',      regionalName: 'Asia Pacífico', active: true },
  {name: 'europe-central2',         displayName: 'Poland, Warsaw',                regionalDisplayName: '(Europa) Poland, Warsaw',                   regionalName: 'Europa',        active: true },
  {name: 'europe-north1',           displayName: 'Finland, Hamina',               regionalDisplayName: '(Europa) Finland, Hamina',                  regionalName: 'Europa',        active: true },
  {name: 'europe-north2',           displayName: 'Sweden, Stockholm',             regionalDisplayName: '(Europa) Sweden, Stockholm',                regionalName: 'Europa',        active: true },
  {name: 'europe-southwest1',       displayName: 'Spain, Madrid',                 regionalDisplayName: '(Europa) Spain, Madrid',                    regionalName: 'Europa',        active: true },
  {name: 'europe-west1',            displayName: 'Belgium, St. Ghislain',         regionalDisplayName: '(Europa) Belgium, St. Ghislain',            regionalName: 'Europa',        active: true },
  {name: 'europe-west10',           displayName: 'Germany, Berlin',               regionalDisplayName: '(Europa) Germany, Berlin',                  regionalName: 'Europa',        active: true },
  {name: 'europe-west12',           displayName: 'Italy, Turin',                  regionalDisplayName: '(Europa) Italy, Turin',                     regionalName: 'Europa',        active: true },
  {name: 'europe-west2',            displayName: 'England, London',               regionalDisplayName: '(Europa) England, London',                  regionalName: 'Europa',        active: true },
  {name: 'europe-west3',            displayName: 'Germany, Francfort',            regionalDisplayName: '(Europa) Germany, Francfort',               regionalName: 'Europa',        active: true },
  {name: 'europe-west4',            displayName: 'Netherlands, Eemshaven',        regionalDisplayName: '(Europa) Netherlands, Eemshaven',           regionalName: 'Europa',        active: true },
  {name: 'europe-west6',            displayName: 'Switzerland, Zurich',           regionalDisplayName: '(Europa) Switzerland, Zurich',              regionalName: 'Europa',        active: true },
  {name: 'europe-west8',            displayName: 'Italy, Milan',                  regionalDisplayName: '(Europa) Italy, Milan',                     regionalName: 'Europa',        active: true },
  {name: 'europe-west9',            displayName: 'France, Paris',                 regionalDisplayName: '(Europa) France, Paris',                    regionalName: 'Europa',        active: true },
  {name: 'me-central1',             displayName: 'Qatar, Doha',                   regionalDisplayName: '(Oriente Medio) Qatar, Doha',               regionalName: 'Oriente Medio', active: true },
  {name: 'me-central2',             displayName: 'Saudi Arabia, Dammam',          regionalDisplayName: '(Oriente Medio) Saudi Arabia, Dammam ',     regionalName: 'Oriente Medio', active: true },
  {name: 'me-west1',                displayName: 'Israel, Tel Aviv',              regionalDisplayName: '(Oriente Medio) Israel, Tel Aviv',          regionalName: 'Oriente Medio', active: true },
  {name: 'northamerica-northeast1', displayName: 'Québec, Montréal',              regionalDisplayName: '(América del Norte) Québec, Montréal',      regionalName: 'América',       active: true },
  {name: 'northamerica-northeast2', displayName: 'Ontario, Toronto',              regionalDisplayName: '(América del Norte) Ontario, Toronto',      regionalName: 'América',       active: true },
  {name: 'northamerica-south1',     displayName: 'Mexico, Queretaro',             regionalDisplayName: '(América del Norte) Mexico, Queretaro',     regionalName: 'América',       active: true },
  {name: 'southamerica-east1',      displayName: 'Brazil, Sao Paulo',             regionalDisplayName: '(América del Sur) Brazil, Sao Paulo',       regionalName: 'América',       active: true },
  {name: 'southamerica-west1',      displayName: 'Chile, Santiago',               regionalDisplayName: '(América del Sur) Chile, Santiago',         regionalName: 'América',       active: true },
  {name: 'us-central1',             displayName: 'Iowa, Council Bluffs',          regionalDisplayName: '(EE.UU.) Iowa, Council Bluffs',             regionalName: 'América',       active: true },
  {name: 'us-east1',                displayName: 'South Carolina, Moncks Corner', regionalDisplayName: '(EE.UU.) South Carolina, Moncks Corner',    regionalName: 'América',       active: true },
  {name: 'us-east4',                displayName: 'Virginia, Ashburn',             regionalDisplayName: '(EE.UU.) Virginia, Ashburn',                regionalName: 'América',       active: true },
  {name: 'us-east5',                displayName: 'Ohio, Columbus',                regionalDisplayName: '(EE.UU.) Ohio, Columbus',                   regionalName: 'América',       active: true },
  {name: 'us-south1',               displayName: 'Texas, Dallas',                 regionalDisplayName: '(EE.UU.) Texas, Dallas',                    regionalName: 'América',       active: true },
  {name: 'us-west1',                displayName: 'Oregon, The Dalles',            regionalDisplayName: '(EE.UU.) Oregon, The Dalles',               regionalName: 'América',       active: true },
  {name: 'us-west2',                displayName: 'California, Los Angeles',       regionalDisplayName: '(EE.UU.) California, Los Angeles',          regionalName: 'América',       active: true },
  {name: 'us-west3',                displayName: 'Utah, Salt Lake City',          regionalDisplayName: '(EE.UU.) Utah, Salt Lake City',             regionalName: 'América',       active: true },
  {name: 'us-west4',                displayName: 'Nevada, Las Vegas',             regionalDisplayName: '(EE.UU.) Nevada, Las Vegas',                regionalName: 'América',       active: true },
  {name: 'us-west8',                displayName: 'Arizona, Phoenix',              regionalDisplayName: '(EE.UU.) Arizona, Phoenix',                 regionalName: 'América',       active: true },
] as const